//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Diagramma
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// График.
    /// </summary>
    // *** Start programmer edit section *** (График CustomAttributes)

    // *** End programmer edit section *** (График CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГрафикE", new string[] {
            "IDсотрдника as \'I dсотрдника\'"})]
    [View("ГрафикL", new string[] {
            "IDсотрдника as \'I dсотрдника\'"})]
    public class График : ICSSoft.STORMNET.DataObject
    {
        
        private bool fЯвка;
        
        private int fIDсотрдника;
        
        private System.DateTime fДата;
        
        private string fПричина;
        
        private int fКол_часов;
        
        private IIS.Diagramma.Сотрудник fСотрудник;
        
        // *** Start programmer edit section *** (График CustomMembers)

        // *** End programmer edit section *** (График CustomMembers)

        
        /// <summary>
        /// IDсотрдника.
        /// </summary>
        // *** Start programmer edit section *** (График.IDсотрдника CustomAttributes)

        // *** End programmer edit section *** (График.IDсотрдника CustomAttributes)
        public virtual int IDсотрдника
        {
            get
            {
                // *** Start programmer edit section *** (График.IDсотрдника Get start)

                // *** End programmer edit section *** (График.IDсотрдника Get start)
                int result = this.fIDсотрдника;
                // *** Start programmer edit section *** (График.IDсотрдника Get end)

                // *** End programmer edit section *** (График.IDсотрдника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (График.IDсотрдника Set start)

                // *** End programmer edit section *** (График.IDсотрдника Set start)
                this.fIDсотрдника = value;
                // *** Start programmer edit section *** (График.IDсотрдника Set end)

                // *** End programmer edit section *** (График.IDсотрдника Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (График.Дата CustomAttributes)

        // *** End programmer edit section *** (График.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (График.Дата Get start)

                // *** End programmer edit section *** (График.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (График.Дата Get end)

                // *** End programmer edit section *** (График.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (График.Дата Set start)

                // *** End programmer edit section *** (График.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (График.Дата Set end)

                // *** End programmer edit section *** (График.Дата Set end)
            }
        }
        
        /// <summary>
        /// Кол_часов.
        /// </summary>
        // *** Start programmer edit section *** (График.Кол_часов CustomAttributes)

        // *** End programmer edit section *** (График.Кол_часов CustomAttributes)
        public virtual int Кол_часов
        {
            get
            {
                // *** Start programmer edit section *** (График.Кол_часов Get start)

                // *** End programmer edit section *** (График.Кол_часов Get start)
                int result = this.fКол_часов;
                // *** Start programmer edit section *** (График.Кол_часов Get end)

                // *** End programmer edit section *** (График.Кол_часов Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (График.Кол_часов Set start)

                // *** End programmer edit section *** (График.Кол_часов Set start)
                this.fКол_часов = value;
                // *** Start programmer edit section *** (График.Кол_часов Set end)

                // *** End programmer edit section *** (График.Кол_часов Set end)
            }
        }
        
        /// <summary>
        /// Причина.
        /// </summary>
        // *** Start programmer edit section *** (График.Причина CustomAttributes)

        // *** End programmer edit section *** (График.Причина CustomAttributes)
        [StrLen(255)]
        public virtual string Причина
        {
            get
            {
                // *** Start programmer edit section *** (График.Причина Get start)

                // *** End programmer edit section *** (График.Причина Get start)
                string result = this.fПричина;
                // *** Start programmer edit section *** (График.Причина Get end)

                // *** End programmer edit section *** (График.Причина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (График.Причина Set start)

                // *** End programmer edit section *** (График.Причина Set start)
                this.fПричина = value;
                // *** Start programmer edit section *** (График.Причина Set end)

                // *** End programmer edit section *** (График.Причина Set end)
            }
        }
        
        /// <summary>
        /// Явка.
        /// </summary>
        // *** Start programmer edit section *** (График.Явка CustomAttributes)

        // *** End programmer edit section *** (График.Явка CustomAttributes)
        public virtual bool Явка
        {
            get
            {
                // *** Start programmer edit section *** (График.Явка Get start)

                // *** End programmer edit section *** (График.Явка Get start)
                bool result = this.fЯвка;
                // *** Start programmer edit section *** (График.Явка Get end)

                // *** End programmer edit section *** (График.Явка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (График.Явка Set start)

                // *** End programmer edit section *** (График.Явка Set start)
                this.fЯвка = value;
                // *** Start programmer edit section *** (График.Явка Set end)

                // *** End programmer edit section *** (График.Явка Set end)
            }
        }
        
        /// <summary>
        /// График.
        /// </summary>
        // *** Start programmer edit section *** (График.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (График.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Diagramma.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (График.Сотрудник Get start)

                // *** End programmer edit section *** (График.Сотрудник Get start)
                IIS.Diagramma.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (График.Сотрудник Get end)

                // *** End programmer edit section *** (График.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (График.Сотрудник Set start)

                // *** End programmer edit section *** (График.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (График.Сотрудник Set end)

                // *** End programmer edit section *** (График.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГрафикE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрафикE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрафикE", typeof(IIS.Diagramma.График));
                }
            }
            
            /// <summary>
            /// "ГрафикL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрафикL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрафикL", typeof(IIS.Diagramma.График));
                }
            }
        }
    }
}
