//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Diagramma
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Таблица.
    /// </summary>
    // *** Start programmer edit section *** (Таблица CustomAttributes)

    // *** End programmer edit section *** (Таблица CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТаблицаE", new string[] {
            "Пособие as \'Пособие\'"})]
    [View("ТаблицаL", new string[] {
            "Пособие as \'Пособие\'"})]
    public class Таблица : ICSSoft.STORMNET.DataObject
    {
        
        private int fЗаработок_год;
        
        private int fСрзаработок;
        
        private int fПособие;
        
        private IIS.Diagramma.Расчет fEmpty;
        
        // *** Start programmer edit section *** (Таблица CustomMembers)

        // *** End programmer edit section *** (Таблица CustomMembers)

        
        /// <summary>
        /// Заработок_год.
        /// </summary>
        // *** Start programmer edit section *** (Таблица.Заработок_год CustomAttributes)

        // *** End programmer edit section *** (Таблица.Заработок_год CustomAttributes)
        public virtual int Заработок_год
        {
            get
            {
                // *** Start programmer edit section *** (Таблица.Заработок_год Get start)

                // *** End programmer edit section *** (Таблица.Заработок_год Get start)
                int result = this.fЗаработок_год;
                // *** Start programmer edit section *** (Таблица.Заработок_год Get end)

                // *** End programmer edit section *** (Таблица.Заработок_год Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Таблица.Заработок_год Set start)

                // *** End programmer edit section *** (Таблица.Заработок_год Set start)
                this.fЗаработок_год = value;
                // *** Start programmer edit section *** (Таблица.Заработок_год Set end)

                // *** End programmer edit section *** (Таблица.Заработок_год Set end)
            }
        }
        
        /// <summary>
        /// Пособие.
        /// </summary>
        // *** Start programmer edit section *** (Таблица.Пособие CustomAttributes)

        // *** End programmer edit section *** (Таблица.Пособие CustomAttributes)
        public virtual int Пособие
        {
            get
            {
                // *** Start programmer edit section *** (Таблица.Пособие Get start)

                // *** End programmer edit section *** (Таблица.Пособие Get start)
                int result = this.fПособие;
                // *** Start programmer edit section *** (Таблица.Пособие Get end)

                // *** End programmer edit section *** (Таблица.Пособие Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Таблица.Пособие Set start)

                // *** End programmer edit section *** (Таблица.Пособие Set start)
                this.fПособие = value;
                // *** Start programmer edit section *** (Таблица.Пособие Set end)

                // *** End programmer edit section *** (Таблица.Пособие Set end)
            }
        }
        
        /// <summary>
        /// Срзаработок.
        /// </summary>
        // *** Start programmer edit section *** (Таблица.Срзаработок CustomAttributes)

        // *** End programmer edit section *** (Таблица.Срзаработок CustomAttributes)
        public virtual int Срзаработок
        {
            get
            {
                // *** Start programmer edit section *** (Таблица.Срзаработок Get start)

                // *** End programmer edit section *** (Таблица.Срзаработок Get start)
                int result = this.fСрзаработок;
                // *** Start programmer edit section *** (Таблица.Срзаработок Get end)

                // *** End programmer edit section *** (Таблица.Срзаработок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Таблица.Срзаработок Set start)

                // *** End programmer edit section *** (Таблица.Срзаработок Set start)
                this.fСрзаработок = value;
                // *** Start programmer edit section *** (Таблица.Срзаработок Set end)

                // *** End programmer edit section *** (Таблица.Срзаработок Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Diagramma.Расчет.
        /// </summary>
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Расчет"})]
        public virtual IIS.Diagramma.Расчет Empty
        {
            get
            {
                IIS.Diagramma.Расчет result = this.fEmpty;
                return result;
            }
            set
            {
                this.fEmpty = value;
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТаблицаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТаблицаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТаблицаE", typeof(IIS.Diagramma.Таблица));
                }
            }
            
            /// <summary>
            /// "ТаблицаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТаблицаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТаблицаL", typeof(IIS.Diagramma.Таблица));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Таблица.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТаблица CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТаблица CustomAttributes)
    public class DetailArrayOfТаблица : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Diagramma.DetailArrayOfТаблица members)

        // *** End programmer edit section *** (IIS.Diagramma.DetailArrayOfТаблица members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Таблица by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Таблица.
        /// </summary>
        public DetailArrayOfТаблица(IIS.Diagramma.Расчет fРасчет) : 
                base(typeof(Таблица), ((ICSSoft.STORMNET.DataObject)(fРасчет)))
        {
        }
        
        public IIS.Diagramma.Таблица this[int index]
        {
            get
            {
                return ((IIS.Diagramma.Таблица)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Diagramma.Таблица dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
